
spring:
  application:
    name: sgescolar 
  datasource:    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/sisescolar
    username: sa
    password: 
  jpa:    hibernate:      ddl-auto: update
    generate-ddl: true
    show-sql: true
  h2:    console:      path: /h2-console
      enabled: true
    
server:
    port: 8080
    
springdoc:
  swagger-ui:
    path: /swagger-ui
    
jwt:
  secret: SGEscolar_#@%_)(98a_).$$BFBGDI&¨%XX