
spring:
  application:
    name: sgescolar 
  datasource:    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sgescolar
    username: postgres
    password: postgres
  jpa:       hibernate:      ddl-auto: update
    generate-ddl: true
    show-sql: true
 
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      
server:
    port: 8080
    
springdoc:
  swagger-ui:
    path: /swagger-ui
    
jwt:
  secret: SGEscolar_#@%_)(98a_).$$BFBGDI&¨%XX